### ISSUE TITLE
Option to only hard-merge booleans

### ISSUE THREAD

**Issue by Kaishiyoku** [codsen/object-merge-advanced#6]
At the moment I'm using merge with the `hardMergeEverything` set to true but that also overrides sub-objects instead of merging them together.

The logical conjunction (AND) of booleans doesn't help me because of the fact that I can't make a falsy value truthy.

Similar goes for logical disjunction (OR) where a falsy value doesn't override a truthy one.

I often have to switch flags and thus I just need to change false to true or vice-versa and always filling hardMergeKeys isn't a good solution because in 95% of my cases I need the boolean-override.

Would it be possible to serve a new option regarding this behavior?

**Comment by revelt** [comment]
hi @Kaishiyoku 

The only solution using current version is to use `null` as explicit `false`. I had the same problem - I needed explicit `false`, second type of `false`, which would override `true` or `false` and yield `false`. That's opts setting `opts.useNullAsExplicitFalse = true`. If this is enabled, `null` on any side trumps any Boolean and yields `false`.

Does your data structure allow such digressions to switch to `null`?

Having said that, your proposed feature is very logical and I'll think how can we implement it. I coded similar thing (just on smaller scale) on [check-types-mini](https://github.com/codsen/check-types-mini), providing optional granular "schema" for any and each key type the user wants to define. Just in this case that would be opts setting to force unidirectional merges for each of 10 types.

**Comment by Kaishiyoku** [comment]
Hi @revelt 

currently my data structure doesn't allow null on boolean values. For my purposes an opt for only overriding booleans would be sufficient but in general I think a schema for setting every single type would be the best solution. I think of something like hardMergeKeys but instead of keys you define schemas.

**Comment by revelt** [comment]
I'll see what I can do, I'll put this on my todo list. 

@Kaishiyoku What is the latest "deadline" by when (roughly) you need this feature, in order to be still relevant?

**Comment by Kaishiyoku** [comment]
@revelt The end of February would be my deadline due to several workarounds I'm implementing in the meantime. If you have any further questions or for everything else just contact me. I'm glad that you take such issues serious.

**Comment by revelt** [comment]
OK. I'll see what I can do.

**Comment by revelt** [comment]
hi @Kaishiyoku, finally I decided to implement an even more universal solution - a callback. Basically, you can tap the final result the moments before it's about to be written, evaluate both clashing values and about-to-be-returned result, and return either that or something else.

I added the example to readme: https://github.com/codsen/object-merge-advanced#optscb-bigger-example-number-one

Let me know how it goes and can we close this ticket.

**Comment by Kaishiyoku** [comment]
Hi @revelt,

Thank you for the fast implementation and all I can say is that the callback-type of implementation is absolutely sufficient for my cases.

It got even better: With the removal of the op.hardMergeEverything = true I also no longer could override objects with a null value which I also handled with the callback.

**Comment by revelt** [comment]
hehe good to hear! have a great day! closing
